language: node_js
node_js: stable
branches:
  only:
  - Root
addons:
  ssh_known_hosts:
  - github.com
  - ssh.github.com
before_install:
- export TZ='Asia/Shanghai'
dd:
- openssl aes-256-cbc -K $encrypted_2bae0f9d1d0b_key -iv $encrypted_2bae0f9d1d0b_iv -in travis_key.enc -out ~/.ssh/id_rsa -d
cache:
  directories:
  - node_modules
install:
- npm install -g hexo-cli
- npm install
script:
- hexo clean
- hexo d -g
