language: node_js
node_js: stable
branches:
  only:
  - Root
before_install:
- export TZ='Asia/Shanghai'
cache:
  directories:
  - node_modules
install:
- npm install -g hexo-cli
- npm install
dd:
- openssl aes-256-cbc -K $encrypted_2bae0f9d1d0b_key -iv $encrypted_2bae0f9d1d0b_iv
  -in travis_key.enc -out travis_key -d
addons:
  ssh_known_hosts:
  - github.com
  - ssh.github.com
script:
- hexo clean
- hexo d -g
